local SkillTable = {
    [1001] = {skillID=1001,skillQuality=1,skillName='Strike',runeCostTable= {air=1,earth=1,water=1,fire=1},animationID = nil,particleID = nil,growthRatio = 2,CD = 1,effectTable ={effectID1=1001,effectValue1=50,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Basic Strike Attack'},
    [1002] = {skillID=1002,skillQuality=2,skillName='Wind Sword',runeCostTable= {air=1,earth=0,water=0,fire=0},animationID = nil,particleID = nil,growthRatio = 2,CD = 1,effectTable ={effectID1=1002,effectValue1=25,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Basic Wind Attack'},
    [1003] = {skillID=1003,skillQuality=3,skillName='Wind Arrow',runeCostTable= {air=2,earth=0,water=0,fire=0},animationID = nil,particleID = nil,growthRatio = 2,CD = 1,effectTable ={effectID1=1002,effectValue1=50,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Advanced Wind Attack'},
    [1004] = {skillID=1004,skillQuality=2,skillName='Stone Sword',runeCostTable= {air=0,earth=1,water=0,fire=0},animationID = nil,particleID = nil,growthRatio = 2,CD = 1,effectTable ={effectID1=1003,effectValue1=25,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Basic Stone Attack'},
    [1005] = {skillID=1005,skillQuality=3,skillName='Stone Arrow',runeCostTable= {air=0,earth=2,water=0,fire=0},animationID = nil,particleID = nil,growthRatio = 2,CD = 1,effectTable ={effectID1=1003,effectValue1=50,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Advanced Stone Attack'},
    [1006] = {skillID=1006,skillQuality=2,skillName='Water Sword',runeCostTable= {air=0,earth=0,water=1,fire=0},animationID = nil,particleID = nil,growthRatio = 2,CD = 1,effectTable ={effectID1=1004,effectValue1=25,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Basic Water Attack'},
    [1007] = {skillID=1007,skillQuality=3,skillName='Water Arrow',runeCostTable= {air=0,earth=0,water=2,fire=0},animationID = nil,particleID = nil,growthRatio = 2,CD = 1,effectTable ={effectID1=1004,effectValue1=50,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Advanced Water Attack'},
    [1008] = {skillID=1008,skillQuality=2,skillName='Fire Sword',runeCostTable= {air=0,earth=0,water=0,fire=1},animationID = nil,particleID = nil,growthRatio = 2,CD = 1,effectTable ={effectID1=1005,effectValue1=25,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Basic Fire Attack'},
    [1009] = {skillID=1009,skillQuality=3,skillName='Fire Arrow',runeCostTable= {air=0,earth=0,water=0,fire=2},animationID = nil,particleID = nil,growthRatio = 2,CD = 1,effectTable ={effectID1=1005,effectValue1=50,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Advanced Fire Attack'},
    [1100] = {skillID=1100,skillQuality=4,skillName='Minor Heal',runeCostTable = {air=0,earth=0,water=2,fire=0},animationID = nil,particleID = nil,growthRatio = 5,CD = 2,effectTable={effectID1=1010,effectValue1=100,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Minor Healing'},
    [1200] = {skillID=1200,skillQuality=4,skillName='Minor Shell',runeCostTable = {air=0,earth=1,water=0,fire=0},animationID = nil,particleID = nil,growthRatio = 5,CD = 5,effectTable={effectID1=1020,effectValue1=100,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Minor Shell'},
    [1300] = {skillID=1300,skillQuality=5,skillName='Minor Recovery',runeCostTable = {air=2,earth=0,water=2,fire=0},animationID = nil,particleID = nil,growthRatio = 2,CD = 2,effectTable={effectID1=1030,effectValue1=100,effectID2=1030,effectValue2=9,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Minor Recovery'},
    [1400] = {skillID=1400,skillQuality=6,skillName='Minor Bleed',runeCostTable = {air=0,earth=0,water=0,fire=3},animationID = nil,particleID = nil,growthRatio = 3,CD = 3,effectTable={effectID1=1040,effectValue1=100,effectID2=1040,effectValue2=10,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Minor Bleed'},
    [1500] = {skillID=1500,skillQuality=4,skillName='Minor Silence',runeCostTable = {air=1,earth=1,water=1,fire=1},animationID = nil,particleID = nil,growthRatio = 10,CD = 10,effectTable={effectID1=1050,effectValue1=0,effectID2=1050,effectValue2=20,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Minor Silence'},
    [1600] = {skillID=1600,skillQuality=4,skillName='Minor Bless',runeCostTable = {air=1,earth=1,water=0,fire=0},animationID = nil,particleID = nil,growthRatio = 10,CD = 10,effectTable={effectID1=1060,effectValue1=2,effectID2=1060,effectValue2=20,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Minor Bless'},
    [1700] = {skillID=1700,skillQuality=4,skillName='Minor Curse',runeCostTable = {air=0,earth=1,water=0,fire=1},animationID = nil,particleID = nil,growthRatio = 5,CD = 5,effectTable={effectID1=1070,effectValue1=1,effectID2=1070,effectValue2=20,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Minor Curse'},
    [1800] = {skillID=1800,skillQuality=7,skillName='Minor Bravery',runeCostTable = {air=5,earth=0,water=0,fire=0},animationID = nil,particleID = nil,growthRatio = 10,CD = 10,effectTable={effectID1=1080,effectValue1=1.5,effectID2=1080,effectValue2=20,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Minor Bravery'},
    [1900] = {skillID=1900,skillQuality=7,skillName='Minor Fear',runeCostTable = {air=0,earth=5,water=0,fire=0},animationID = nil,particleID = nil,growthRatio = 10,CD = 10,effectTable={effectID1=1090,effectValue1=0.5,effectID2=1090,effectValue2=20,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Minor Fear'},   
    [2000] = {skillID=2000,skillQuality=1,skillName='Minor Purify',runeCostTable = {air=2,earth=2,water=2,fire=2},animationID = nil,particleID = nil,growthRatio = 10, CD = 10, effectTable={effectID1=1100,effectValue1=nil,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Minor Fear'},
    [2100] = {skillID=2100,skillQuality=1,skillName='Minor Disperse',runeCostTable = {air=2,earth=2,water=2,fire=2},animationID = nil,particleID = nil,growthRatio = 10, CD = 10, effectTable={effectID1=1110,effectValue1=nil,effectID2=nil,effectValue2=nil,effectID3=nil,effectValue3=nil},skillSum='',skillDesc='Minor Fear'},
}


return SkillTable

-- Note: The continous Skill will consume the first and second effect slot to store both the value and duration
-- of that skill.